---
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080 # Sabnzbd
      - 8085:8085 # qBittorrent
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 6767:6767 # Bazarr
      - 7878:7878 # Radarr
      - 9705:9705 # Huntarr
    environment:
      - TZ=${TZ}
      - UPDATER_PERIOD=24h
      # VPN Configuration
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - PORT_FORWARDING_PROVIDER=${VPN_PROVIDER}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      # qBittorrent Configuration
      - PORT_FORWARDING=on
      - QBITTORRENT=on
      - QBITTORRENT_HOST=localhost
      - QBITTORRENT_PORT=8085
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8085/api/v2/app/setPreferences 2>&1'
    volumes:
      - ./media-management/gluetun:/gluetun
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8085
    volumes:
      - ./media-management/qbittorrent:/config
      - ${MEDIA_DIR}/Downloads/complete:/downloads
    depends_on:
      - gluetun
    restart: always

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./media-management/sabnzbd/config:/config
      - ${MEDIA_DIR}/Downloads/incomplete:/incomplete #optional
      - ${MEDIA_DIR}/Downloads/complete:/downloads #optional
    depends_on:
      - gluetun
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./media-management/sonarr/data:/config
      - "${MEDIA_DIR}/Library/TV Shows:/tv"
      - ${MEDIA_DIR}/Library/Anime:/anime
      - ${MEDIA_DIR}/Downloads/incomplete:/incomplete
      - ${MEDIA_DIR}/Downloads/complete:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./media-management/radarr/data:/config
      - ${MEDIA_DIR}/Library/Movies:/movies
      - ${MEDIA_DIR}/Library/Anime:/anime
      - ${MEDIA_DIR}/Downloads/incomplete:/incomplete
      - ${MEDIA_DIR}/Downloads/complete:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./media-management/prowlarr/data:/config
    depends_on:
      - gluetun
    restart: unless-stopped

  bazarr:
    image: ghcr.io/hotio/bazarr:latest
    container_name: bazarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./media-management/bazarr/config:/config
      - ./media-management/bazarr/data:/data
      - ${MEDIA_DIR}/Library/Movies:/movies
      - "${MEDIA_DIR}/Library/TV Shows:/tv"
      - ${MEDIA_DIR}/Library/Anime:/anime
    restart: unless-stopped

  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    network_mode: "service:gluetun"
    environment:
      - TZ=${TZ}
    volumes:
      - ./media-management/huntarr:/config
    restart: unless-stopped
