---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./jellyfin:/config
      - "${MEDIA_DIR}/Library/TV Shows:/data/tvshows"
      - ${MEDIA_DIR}/Library/Movies:/data/movies
      - ${MEDIA_DIR}/Library/Anime:/data/anime
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - ./jellyseer:/app/config
    restart: unless-stopped

  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    ports:
      - 5690:5690
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DISABLE_BUILTIN_AUTH=false
      - TZ=${TZ}
    volumes:
      - ./wizarr/config/database:/data/database
      - ./wizarr/config/wizard:/data/wizard_steps
    restart: unless-stopped

